### ISSUE TITLE
Route - Parameters with Names does not work

### ISSUE THREAD

**Issue by Chameleon-m** [scento/phalcon-php#42]
Warning: Missing argument 1 for {closure}() in ...
Notice: Undefined variable: id in ...
```php
// . . .
$app = new \Phalcon\Mvc\Micro($di);

$app->put('/api/v1/statistics/user/viewhandbook/{id:[0-9]+}', function($id) use ($app) {
var_dump($id);die;
// ...
});
$app->handle();
```
Sorry, but unfortunately I don't have time to fix. Maybe on the weekend will be a time.

**Comment by scento** [comment]
As described in the `Readme.md`s disclaimer I stopped developing this project, but if I can get some free time, I will setup my development environment again and test your usecase.

**Comment by scento** [comment]
I found the bug triggering the Exception. If you experience some other problems related to this one, please let me know...
